### ISSUE TITLE
NumberInput & Decimal Input Enhacements

### ISSUE THREAD

**Issue by hanidelneri** [karianpour/react-hichestan-numberinput#5]
- [ ] add a new property to number input which allows to emit javascript number instead of string.

- [ ] add a new property to decimal input which hides the separators.

**Comment by karianpour** [comment]
After version 1.0.9 you can use `DecimalInput` as follow to remove thousand separator:

```jsx
<DecimalInput  thousandSeparator=''/>
```


For `NumberInput` to return javascript number, just use `DecimalInput` with no thousand separator.
